(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var k=this||self,aa=function(a){a:{var b=["CLOSURE_FLAGS"];for(var c=k,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}a=b&&b[a];return null!=a?a:!1},n=function(a){return a};function ba(a){k.setTimeout(()=>{throw a;},0)};var ca=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};var da=aa(610401301),ea=aa(188588736);var q;const fa=k.navigator;q=fa?fa.userAgentData||null:null;function ha(a){return da?q?q.brands.some(({brand:b})=>b&&-1!=b.indexOf(a)):!1:!1}function r(a){var b;a:{if(b=k.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)};function t(){return da?!!q&&0<q.brands.length:!1}function ia(){return t()?ha("Chromium"):(r("Chrome")||r("CriOS"))&&!(t()?0:r("Edge"))||r("Silk")};var ja=t()?!1:r("Trident")||r("MSIE");!r("Android")||ia();ia();r("Safari")&&(ia()||(t()?0:r("Coast"))||(t()?0:r("Opera"))||(t()?0:r("Edge"))||(t()?ha("Microsoft Edge"):r("Edg/"))||t()&&ha("Opera"));var ka={},u=null;var la="undefined"!==typeof Uint8Array,ma=!ja&&"function"===typeof btoa;function qa(a){return"function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol():a}var v=qa(),ra=qa("2ex");var sa=v?(a,b)=>{a[v]|=b}:(a,b)=>{void 0!==a.g?a.g|=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}})};function w(a,b,c){return c?a|b:a&~b}var x=v?a=>a[v]|0:a=>a.g|0,z=v?a=>a[v]:a=>a.g,A=v?(a,b)=>{a[v]=b;return a}:(a,b)=>{void 0!==a.g?a.g=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}});return a};function ta(a,b){A(b,(a|0)&-14591)}function ua(a,b){A(b,(a|34)&-14557)}function va(a){a=a>>14&1023;return 0===a?536870912:a};var B={},wa={};function xa(a){return!(!a||"object"!==typeof a||a.g!==wa)}function ya(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}let za;function D(a,b,c){if(!Array.isArray(a)||a.length)return!1;const d=x(a);if(d&1)return!0;if(!(b&&(Array.isArray(b)?b.includes(c):b.has(c))))return!1;A(a,d|1);return!0}var Aa;const Ba=[];A(Ba,55);Aa=Object.freeze(Ba);class Ca{}class Da{}Object.freeze(new Ca);Object.freeze(new Da);let Ea;function Fa(a){if(null==a)return a;if("string"===typeof a){if(!a)return;a=+a}if("number"===typeof a)return Number.isFinite(a)?a|0:void 0}function Ga(a,b,c){if(null!=a&&"object"===typeof a&&a.i===B)return a;if(Array.isArray(a)){var d=x(a),g=d;0===g&&(g|=c&32);g|=c&2;g!==d&&A(a,g);return new b(a)}};let E;function Ha(a,b){E=b;a=new a(b);E=void 0;return a};function Ia(a,b){return Ja(b)}
function Ja(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "boolean":return a?1:0;case "object":if(a)if(Array.isArray(a)){if(D(a,void 0,0))return}else if(la&&null!=a&&a instanceof Uint8Array){if(ma){for(var b="",c=0,d=a.length-10240;c<d;)b+=String.fromCharCode.apply(null,a.subarray(c,c+=10240));b+=String.fromCharCode.apply(null,c?a.subarray(c):a);a=btoa(b)}else{void 0===b&&(b=0);if(!u){u={};c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split("");d=["+/=",
"+/","-_=","-_.","-_"];for(var g=0;5>g;g++){var e=c.concat(d[g].split(""));ka[g]=e;for(var h=0;h<e.length;h++){var f=e[h];void 0===u[f]&&(u[f]=h)}}}b=ka[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(g=e=0;e<a.length-2;e+=3){var m=a[e],l=a[e+1];f=a[e+2];h=b[m>>2];m=b[(m&3)<<4|l>>4];l=b[(l&15)<<2|f>>6];f=b[f&63];c[g++]=""+h+m+l+f}h=0;f=d;switch(a.length-e){case 2:h=a[e+1],f=b[(h&15)<<2]||d;case 1:a=a[e],c[g]=""+b[a>>2]+b[(a&3)<<4|h>>4]+f+d}a=c.join("")}return a}}return a};function Ka(a,b,c){a=Array.prototype.slice.call(a);var d=a.length;const g=b&256?a[d-1]:void 0;d+=g?-1:0;for(b=b&512?1:0;b<d;b++)a[b]=c(a[b]);if(g){b=a[b]={};for(const e in g)b[e]=c(g[e])}return a}function La(a,b,c,d,g){if(null!=a){if(Array.isArray(a))a=D(a,void 0,0)?void 0:g&&x(a)&2?a:Ma(a,b,c,void 0!==d,g);else if(ya(a)){const e={};for(let h in a)e[h]=La(a[h],b,c,d,g);a=e}else a=b(a,d);return a}}
function Ma(a,b,c,d,g){const e=d||c?x(a):0;d=d?!!(e&32):void 0;a=Array.prototype.slice.call(a);for(let h=0;h<a.length;h++)a[h]=La(a[h],b,c,d,g);c&&c(e,a);return a}function Na(a){return a.i===B?a.toJSON():Ja(a)};function Oa(a,b,c=ua){if(null!=a){if(la&&a instanceof Uint8Array)return b?a:new Uint8Array(a);if(Array.isArray(a)){var d=x(a);if(d&2)return a;b&&(b=0===d||!!(d&32)&&!(d&64||!(d&16)));return b?A(a,(d|34)&-12293):Ma(a,Oa,d&4?ua:c,!0,!0)}a.i===B&&(c=a.h,d=z(c),a=d&2?a:Ha(a.constructor,Pa(c,d,!0)));return a}}function Pa(a,b,c){const d=c||b&2?ua:ta,g=!!(b&32);a=Ka(a,b,e=>Oa(e,g,d));sa(a,32|(c?2:0));return a}function Qa(a){const b=a.h,c=z(b);return c&2?Ha(a.constructor,Pa(b,c,!1)):a};var Sa=function(a,b){a=a.h;return F(a,z(a),b)};function Ta(a,b,c,d){b=d+(+!!(b&512)-1);if(!(0>b||b>=a.length||b>=c))return a[b]}
var F=function(a,b,c,d){if(-1===c)return null;const g=va(b);if(c>=g){if(b&256)return a[a.length-1][c]}else{var e=a.length;if(d&&b&256&&(d=a[e-1][c],null!=d)){if(Ta(a,b,g,c)&&null!=ra){var h;a=null!=(h=Ea)?h:Ea={};h=a[ra]||0;4<=h||(a[ra]=h+1,h=Error(),h.__closure__error__context__984382||(h.__closure__error__context__984382={}),h.__closure__error__context__984382.severity="incident",ba(h))}return d}return Ta(a,b,g,c)}};
function G(a,b,c,d,g){const e=va(b);if(c>=e||g){let h=b;if(b&256)g=a[a.length-1];else{if(null==d)return h;g=a[e+(+!!(b&512)-1)]={};h|=256}g[c]=d;c<e&&(a[c+(+!!(b&512)-1)]=void 0);h!==b&&A(a,h);return h}a[c+(+!!(b&512)-1)]=d;b&256&&(a=a[a.length-1],c in a&&delete a[c]);return b}var K=function(a,b,c){return void 0!==H(a,b,I(a,J,c))},Ua=function(a,b){a=Sa(a,b);return null==a||"boolean"===typeof a?a:"number"===typeof a?!!a:void 0};function Va(a){return!!(2&a)&&!!(4&a)||!!(2048&a)}
function Wa(a,b,c,d){const g=a.h;let e=z(g);if(e&2)throw Error();G(g,e,b,("0"===d?0===Number(c):c===d)?void 0:c);return a}var I=function(a,b,c){a=a.h;return Xa(a,z(a),b)===c?c:-1};function Xa(a,b,c){let d=0;for(let g=0;g<c.length;g++){const e=c[g];null!=F(a,b,e)&&(0!==d&&(b=G(a,b,d)),d=e)}return d}function H(a,b,c,d){a=a.h;let g=z(a);const e=F(a,g,c,d);b=Ga(e,b,g);b!==e&&null!=b&&G(a,g,c,b,d);return b}
var L=function(a,b,c){b=H(a,b,c,!1);if(null==b)return b;a=a.h;let d=z(a);if(!(d&2)){const g=Qa(b);g!==b&&(b=g,G(a,d,c,b,!1))}return b},$a=function(a,b){a=a.h;var c=z(a),d=c,g=!(2&c),e=!!(2&d),h=e?1:2;c=1===h;h=2===h;g&&(g=!e);e=F(a,d,b);e=Array.isArray(e)?e:Aa;var f=x(e);const m=!!(4&f);if(!m){var l=f;0===l&&(l=Ya(l,d));l=w(l,1,!0);f=e;var y=d,C=Za;const p=!!(2&l);p&&(y=w(y,2,!0));let N=!p,na=!0,U=0,oa=0;for(;U<f.length;U++){const pa=Ga(f[U],C,y);if(pa instanceof C){if(!p){const Ra=!!(x(pa.h)&2);
N&&(N=!Ra);na&&(na=Ra)}f[oa++]=pa}}oa<U&&(f.length=oa);l=w(l,4,!0);l=w(l,16,na);l=w(l,8,N);A(f,l);p&&Object.freeze(f);f=l}l=!!(8&f)||c&&!e.length;if(g&&!l){Va(f)&&(e=Array.prototype.slice.call(e),f=Ya(f,d),d=G(a,d,b,e));g=e;for(l=0;l<g.length;l++)y=g[l],C=Qa(y),y!==C&&(g[l]=C);f=w(f,8,!0);f=w(f,16,!g.length);A(g,f)}Va(f)||(g=f,c?f=w(f,!e.length||16&f&&(!m||32&f)?2:2048,!0):f=w(f,32,!1),f!==g&&A(e,f),c&&Object.freeze(e));h&&Va(f)&&(e=Array.prototype.slice.call(e),f=Ya(f,d),A(e,f),G(a,d,b,e));return e};
function Ya(a,b){a=w(a,2,!!(2&b));a=w(a,32,!!(32&b)&&!1);return a=w(a,2048,!1)}var M=function(a,b){a=Ua(a,b);return null!=a?a:!1},O=function(a,b){a=Fa(Sa(a,b));return null!=a?a:0},P=function(a,b){a=Sa(a,b);a=null==a||"string"===typeof a?a:void 0;return null!=a?a:""};var Q=class{constructor(a){a:{null==a&&(a=E);E=void 0;if(null==a){var b=96;a=[]}else{if(!Array.isArray(a))throw Error();b=x(a);if(b&2048)throw Error();if(b&64)break a;var c=a;b|=64;var d=c.length;if(d&&(--d,ya(c[d]))){b|=256;c=d-(+!!(b&512)-1);if(1024<=c)throw Error();b=b&-16760833|(c&1023)<<14}}A(a,b)}this.h=a}toJSON(){return za?ab(this,this.h,!1):ab(this,Ma(this.h,Na,void 0,void 0,!1),!0)}};Q.prototype.i=B;Q.prototype.toString=function(){return ab(this,this.h,!1).toString()};
function ab(a,b,c){var d=ea?void 0:a.constructor.j;const g=z(c?a.h:b);a=b.length;if(!a)return b;let e,h;if(ya(c=b[a-1])){a:{var f=c;let y={},C=!1;for(var m in f){let p=f[m];if(Array.isArray(p)){let N=p;if(D(p,d,+m)||xa(p)&&0===p.size)p=null;p!=N&&(C=!0)}null!=p?y[m]=p:C=!0}if(C){for(var l in y){f=y;break a}f=null}}f!=c&&(e=!0);a--}for(m=+!!(g&512)-1;0<a;a--){l=a-1;c=b[l];l-=m;if(!(null==c||D(c,d,l)||xa(c)&&0===c.size))break;h=!0}if(!e&&!h)return b;b=Array.prototype.slice.call(b,0,a);f&&b.push(f);
return b};var Za=class extends Q{},R=[2,3,4];var S=class extends Q{};var T=class extends Q{};var bb=class extends Q{};bb.j=[6];var cb=class extends Q{constructor(){super()}};var db=class extends Q{constructor(){super()}},eb=[2];var fb=class extends Q{};fb.j=[2];var gb=class extends Q{};var hb=class extends Q{};var ib=class extends Q{};var jb=function(a){return b=>{if(null==b||""==b)b=new a;else{b=JSON.parse(b);if(!Array.isArray(b))throw Error(void 0);sa(b,32);b=Ha(a,b)}return b}}(class extends Q{}),J=[2,3,4,5,6,7];var V;var kb=class{constructor(a){this.g=a}toString(){return this.g+""}},lb={},mb=function(a){if(void 0===V){var b=null;var c=k.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:n,createScript:n,createScriptURL:n})}catch(d){k.console&&k.console.error(d.message)}V=b}else V=b}a=(b=V)?b.createScriptURL(a):a;return new kb(a,lb)};/*

 SPDX-License-Identifier: Apache-2.0
*/
function nb(a,...b){if(0===b.length)return mb(a[0]);let c=a[0];for(let d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return mb(c)};var W=function(){this.g=document||{cookie:""}};
W.prototype.set=function(a,b,c){let d,g,e,h=!1,f;"object"===typeof c&&(f=c.u,h=c.v||!1,e=c.domain||void 0,g=c.path||void 0,d=c.o);if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');void 0===d&&(d=-1);this.g.cookie=a+"="+b+(e?";domain="+e:"")+(g?";path="+g:"")+(0>d?"":0==d?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(Date.now()+1E3*d)).toUTCString())+(h?";secure":"")+(null!=f?";samesite="+f:"")};
W.prototype.get=function(a,b){const c=a+"=",d=(this.g.cookie||"").split(";");for(let g=0,e;g<d.length;g++){e=ca(d[g]);if(0==e.lastIndexOf(c,0))return e.slice(c.length);if(e==a)return""}return b};
W.prototype.clear=function(){var a=(this.g.cookie||"").split(";");const b=[];var c=[];let d,g;for(let e=0;e<a.length;e++)g=ca(a[e]),d=g.indexOf("="),-1==d?(b.push(""),c.push(g)):(b.push(g.substring(0,d)),c.push(g.substring(d+1)));for(c=b.length-1;0<=c;c--)a=b[c],this.get(a),this.set(a,"",{o:0,path:void 0,domain:void 0})};class ob{constructor(){this.l=new W;this.g="";this.m=a=>{a:{let m;try{m=jb(a.data)}catch(l){break a}if(K(m,bb,4)){var b=L(m,bb,I(m,J,4));var c=$a(b,6);var d;c.length&&(d=pb(c));c={event:P(b,1)||void 0,category:P(b,2)||void 0,action:P(b,3)||void 0,label:P(b,4)||void 0,value:O(b,5)||void 0,nonInteraction:M(b,13)?"True":"False",additionalParams:d||void 0};if(void 0!==H(b,T,12,!1)){var g=L(b,T,12);c.recommendations={targetPage:P(g,1),targetType:O(g,2),targetRank:O(g,3),targetIdenticalDescriptions:O(g,
4),targetTitleWords:O(g,5),targetDescriptionWords:O(g,6),experiment:P(g,7)};d="";for(var e of window.dataLayer)if("experiment"in e&&"baseIds"in e.experiment){d=e.experiment.baseIds;break}(d=qb(d,P(g,7)))&&M(g,8)&&(c.experiment={ids:d})}else c.recommendations={targetPage:void 0,targetType:void 0,targetRank:void 0,targetIdenticalDescriptions:void 0,targetTitleWords:void 0,targetDescriptionWords:void 0};if(!("experiment"in c))for(var h of window.dataLayer)if("experiment"in h&&"ids"in h.experiment&&h.experiment.ids){c.experiment=
{ids:h.experiment.ids};break}e=L(b,S,11);if(void 0!==H(b,S,11,!1)&&null!==e){e=rb(e);for(var f of Object.keys(e))c[f]=e[f]}window.dataLayer.push(c)}else if(K(m,fb,3)){f=L(m,fb,I(m,J,3));e=$a(f,2);let l;e.length&&(l=pb(e));e={event:"trackPageview",pageName:P(f,1),additionalParams:l||void 0,nonInteraction:M(f,3)||void 0,ratingsCount:O(f,4)||void 0,ratingsValue:O(f,5)||void 0};h=L(f,S,6);if(void 0!==H(f,S,6,!1)&&null!==h){f=rb(h);for(b of Object.keys(f))e[b]=f[b]}window.dataLayer.push(e)}else K(m,gb,
7)?(f=L(m,gb,I(m,J,7)),f={parentContext:{referrer:P(f,2)||"",_ga_devsiteCookie:P(f,1)||""}},window.dataLayer.push(f)):K(m,hb,6)?(f=L(m,hb,I(m,J,6)),e=this.g,h=L(f,T,9)||new T,b=P(f,10)||void 0,f={experiment:{ids:(M(h,8)?qb(b,P(h,7)):b)||void 0,baseIds:b||void 0},hostContext:{internalUser:P(f,1)||void 0,pageType:P(f,8)||void 0,projectName:P(f,6)||void 0,signedIn:P(f,2)||void 0,tenant:P(f,5)||void 0,thirdPartyCookieAccepted:e.length?"True":"False"},language:{machineTranslated:P(f,7)||void 0,requested:P(f,
3)||void 0,served:P(f,4)||void 0},recommendations:{sourcePage:P(h,1),sourceType:O(h,2),sourceRank:O(h,3),sourceIdenticalDescriptions:O(h,4),sourceTitleWords:O(h,5),sourceDescriptionWords:O(h,6),experiment:P(h,7)}},window.dataLayer.push(f)):K(m,ib,5)?(f=L(m,ib,I(m,J,5)),f={originalUrlParameters:{dclid:P(f,1)||void 0,gclid:P(f,2)||void 0,utmCampaign:P(f,3)||void 0,utmContent:P(f,4)||void 0,utmCreativeFormat:P(f,8)||void 0,utmMarketingTactic:P(f,10)||void 0,utmMedium:P(f,5)||void 0,utmSource:P(f,6)||
void 0,utmSourcePlatform:P(f,9)||void 0,utmTerm:P(f,7)||void 0}},window.dataLayer.push(f)):null!=Ua(m,I(m,J,2))&&(window.dataLayer=window.dataLayer||[],window.dataLayer.push({"gtm.start":(new Date).getTime(),event:"gtm.js"}),e=document,f=e.getElementsByTagName("script")[0],e=e.createElement("script"),e.async=!0,h=nb`//www.googletagmanager.com/gtm.js?id=GTM-PBZPJDG`,e.src=h instanceof kb&&h.constructor===kb?h.g:"type_error:TrustedResourceUrl",(h=(h=null==(g=(c=(e.ownerDocument&&e.ownerDocument.defaultView||
window).document).querySelector)?void 0:g.call(c,"script[nonce]"))?h.nonce||h.getAttribute("nonce")||"":"")&&e.setAttribute("nonce",h),f.parentNode.insertBefore(e,f))}};window.addEventListener("message",this.m)}s(a){this.g=this.l.get("_ga_devsite")||"";var b=new cb;if(null!=a&&"boolean"!==typeof a){var c=typeof a;throw Error(`Expected boolean but got ${"object"!=c?c:a?Array.isArray(a)?"array":c:"null"}: ${a}`);}a=Wa(b,1,a,!1);b=this.g;if(null!=b&&"string"!==typeof b)throw Error();b=Wa(a,2,b,"");a=
new db;null==b&&(b=void 0);var d=a.h;let g=z(d);if(g&2)throw Error();let e=Xa(d,g,eb);e&&2!==e&&null!=b&&(g=G(d,g,e));G(d,g,2,b);if(window.parent!==window){b=window.parent;d=b.postMessage;a:{za=!0;try{c=JSON.stringify(a.toJSON(),Ia);break a}finally{za=!1}c=void 0}d.call(b,c,"*")}}}ob.prototype.notifyIframeReady=ob.prototype.s;
function pb(a){const b={};for(const c of a){a=P(c,1);let d;P(c,I(c,R,2))?d=P(c,I(c,R,2)):O(c,I(c,R,3))?d=O(c,I(c,R,3)):null!=Ua(c,I(c,R,4))&&(d=M(c,I(c,R,4))?"True":"False");b[a]=d}return b}
function rb(a){const b={};if(!a)return b;b.hasProfile=M(a,6)?"True":"False";b.practitionerType=P(a,1)||"Property not set";b.profileCreationMethod=P(a,4)||"Property not set";b.profileHasInterests=M(a,12)?"True":"False";b.profileInterests=P(a,13)||"Property not set";b.profileHasJobTitle=M(a,10)?"True":"False";b.profileHasLocation=M(a,7)?"True":"False";b.profileHasPronoun=M(a,9)?"True":"False";b.profileIsPublic=M(a,8)?"True":"False";b.profileSocialLinks=P(a,11)||"Property not set";b.profileBadgeEmailOptIn=
M(a,5)?"True":"False";b.profileFeedbackEmailOptIn=M(a,2)?"True":"False";b.profileNewsletterEmailOptIn=M(a,3)?"True":"False";return b}function qb(a,b){if(a||b){if(a&&!b)return a;if(b&&!a)return b;b=new Set(b.split(","));a=[...(new Set([...(new Set(a.split(","))),...b]))];a.sort();return a.join(",")}}var sb=ob,X=["AnalyticsLibrary"],Y=k;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);
for(var Z;X.length&&(Z=X.shift());)X.length||void 0===sb?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=sb;}).call(this);
