(function(_ds){var window=this;var EW=function(){return(0,_ds.X)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},FW=function(){return(0,_ds.X)('<div class="devsite-book-nav-blur"></div>')},GW=function(a){a=a.vw;a=_ds.cK(new _ds.ZJ("{NUMBER_OF_MATCHING_DESCENDANTS,plural,=1{{XXX_1} match}other{{XXX_2} matches}}"),{NUMBER_OF_MATCHING_DESCENDANTS:a,XXX_1:_ds.Y(_ds.as(1)),XXX_2:_ds.Y(_ds.as(a))});return(0,_ds.X)('<span class="devsite-nav-filter-match-count"> (<mark>'+
a+"</mark>)</span>")};var HW="onpointerover"in window?"pointerover":"mouseover",IW=function(a){const b=0<a.querySelectorAll(".devsite-nav-item").length,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.E(a,"visually-hidden","",c))},QW=function(a){a.eventHandler.listen(a,"click",b=>void JW(a,b));a.eventHandler.listen(a,"keypress",b=>{13===b.keyCode&&JW(a,b)});a.eventHandler.listen(a,[HW,"focusin"],b=>void KW(a,b));a.eventHandler.listen(document.body,"devsite-sitemask-hidden",
()=>{a.h&&(LW(a,"_book")?a.removeAttribute("top-level-nav"):_ds.E(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",()=>void a.qa.Ua());a.eventHandler.listen(a,"devsite-content-updated",()=>{a.qa.Ua()});a.eventHandler.listen(a,"scroll",()=>{_ds.E(a,"user-scrolled","")});a.eventHandler.listen(a.Qb,"click",()=>{MW(a)});a.g&&(a.eventHandler.listen(a.g,"keyup",()=>void a.ua.Ua()),a.eventHandler.listen(a.g,"focus",()=>void NW(a,"focus")));a.ea&&a.eventHandler.listen(a.ea,
["click","keydown"],b=>{if("click"===b.type||13===b.keyCode||27===b.keyCode){a.g&&(a.g.value="",a.g.focus());let c;null==(c=a.ea)||c.classList.add("hidden");OW(a);PW(a);NW(a,b.type)}})},SW=function(a,b=a,c=!0){b=Array.from(b.querySelectorAll(".devsite-nav-title"));a.o=new Set(b);if(!_ds.G().hash&&c)RW(a,a.o);else{c=new _ds.qK;for(const d of a.o)_ds.pK(c,d)}},TW=async function(a){const b=await _ds.u();for(const c of a.o)b.unregisterIntersectionForElement(c)},JW=function(a,b){if(!b.defaultPrevented){var c=
b.target;"devsite-close-nav"===c.getAttribute("id")&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.E(a,"top-level-nav",""));if(c.hasAttribute("menu")){var d=c.getAttribute("menu");d&&LW(a,d)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}var e=c.closest(".devsite-expandable-nav");if(e&&(d=c.closest(".devsite-nav-title, .devsite-nav-toggle"))){let f=
b.target,g,h;if(!(null==(g=f)?0:null==(h=g.closest(".devsite-nav-title"))?0:h.hasAttribute("href"))){for(b="click"===b.type||"touchend"===b.type;f&&f!==e;){if(f.classList.contains("devsite-nav-title-no-path")&&b){f.blur();break}f=f.parentNode}e.querySelector(".devsite-nav-section")&&(b=e.classList.toggle("expanded"),(e=e.querySelector(".devsite-nav-title"))&&_ds.E(a,"aria-expanded",`${b}`,e))}if(d.matches(".devsite-nav-toggle"))return}c.closest(".devsite-nav-title-no-path")||(a.h&&(d=a.h.querySelector("[menu=_book]"))&&
d.contains(c)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})),(c=c.closest("a.devsite-nav-title"))&&!c.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})))}},KW=function(a,b){b.defaultPrevented||(b=_ds.Hk(b.target,c=>c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a,!0),b!==a&&_ds.te(b,_ds.ne(_ds.yl(b.href).href)))},MW=async function(a){var b=document.documentElement.scrollHeight-document.documentElement.clientHeight;
const c=b?document.documentElement.scrollTop/b:0;_ds.Sm(a.eventHandler,a,_ds.Hh,()=>{a.removeAttribute("animatable");a.background.removeAttribute("animatable");a.j.removeAttribute("animatable")});_ds.E(a,"animatable","");b=_ds.Ie(a.v`animatable`);b(a.background,"animatable","");b(a.j,"animatable","");a.hasAttribute("collapsed")?(_ds.E(a,"aria-expanded","true",a.Qb),_ds.E(a,"aria-label","Hide side navigation",a.Qb),_ds.E(a,"data-title","Hide side navigation",a.Qb),a.removeAttribute("collapsed"),UW(a,
"Expanded book nav")):(a.Qb.removeAttribute("aria-expanded"),_ds.E(a,"aria-label","Show side navigation",a.Qb),_ds.E(a,"data-title","Show side navigation",a.Qb),_ds.E(a,"collapsed",""),UW(a,"Collapsed book nav"));await _ds.Fl();b=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(c*b)},NW=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:b,label:"focus"===
b?"devsite-book-nav-filter input":"devsite-book-nav-filter filter-clear-button"},bubbles:!0}))},VW=function(a){a.oa=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},XW=function(a){const b=_ds.G().searchParams.get("nf");a.g&&b&&(a.g.value=b,WW(a))},WW=function(a){if(a.oa.length){OW(a);PW(a);var b,c,d=null==(b=a.g)?void 0:null==(c=b.value)?void 0:c.trim().toLowerCase();if(d){var e;null==(e=a.ea)||e.classList.remove("hidden");
for(const g of a.oa){c=g.querySelectorAll(".devsite-nav-text");b=g.classList.contains("devsite-nav-expandable");var f=e=!1;a=0;let h,k;if(d&&b&&(null==(h=g.querySelector(".devsite-nav-text"))?0:null==(k=h.textContent)?0:k.toLowerCase().includes(d)))f=e=!0;else for(const l of c){let m;d&&(null==(m=l.textContent)?0:m.toLowerCase().includes(d))&&(e=!0,++a)}if(!0===e){g.classList.remove("hidden");if(f){c=Array.from(g.querySelectorAll(".devsite-nav-item"));for(const l of c){l.classList.remove("hidden");
let m;d&&(null==(m=l.textContent)?0:m.toLowerCase().includes(d))&&++a}}c=void 0;(f=g.querySelector(".devsite-nav-text"))&&(e=null==(c=f.textContent)?void 0:c.replace(new RegExp(`(${d})`,"ig"),"<mark>$1</mark>"))&&_ds.Ge(f,_ds.Xe(e))}b&&0<a&&(b=g.querySelector(".devsite-nav-text"))&&(a=_ds.O(GW,{vw:a}),b.appendChild(a))}}else null==(f=a.ea)||f.classList.add("hidden")}},OW=function(a){for(const b of a.oa){let c;b.classList.toggle("hidden",!(null==(c=a.g)||!c.value))}},PW=function(a){if(a.querySelector("mark")){var b=
[...a.querySelectorAll(".devsite-nav-text > .devsite-nav-filter-match-count")];for(const c of b)c.remove();a=[...a.querySelectorAll(".devsite-nav-text > mark")];for(const c of a){a=c.parentElement;let d;b=null==(d=a)?void 0:d.textContent;a&&b&&_ds.Ge(a,_ds.Xe(b))}}},RW=async function(a,b){if(a.connected){var c=await _ds.u(),d=new _ds.qK,e=f=>{f=f.target;_ds.pK(d,f);a.o.delete(f);c.unregisterIntersectionForElement(f)};for(const f of b)try{c.registerIntersectionForElement(f,e)}catch(g){e({target:f})}}},
LW=function(a,b){let c=!1;if(a.h)for(const d of a.h.querySelectorAll("[menu]"))d.getAttribute("menu")===b?(d.removeAttribute("hidden"),c=!0):_ds.E(a,"hidden","",d);return c},YW=function(a,b=a){b||(b=a);for(const c of b.querySelectorAll(".devsite-nav-active"))c.classList.remove("devsite-nav-active");a=_ds.Ml(_ds.G().pathname);a=`[href="${_ds.yl(a).href}"], [href="${a}"],
        [alt-paths~="${a}"]`;for(const c of b.querySelectorAll(a))c.classList.add("devsite-nav-active")},ZW=function(a,b=a){b||(b=a);if(a=b.querySelector(".devsite-mobile-nav-bottom"))for(a=a.querySelector(".devsite-nav-active");a&&a.parentElement&&a.parentElement!==b;)a.matches(".devsite-expandable-nav:not(.expanded)")&&a.classList.add("expanded"),a=a.parentElement},aX=async function(a){a.connected&&(a.removeAttribute("user-scrolled"),await _ds.Fl(),await $W(a),await a.va,await _ds.u(),await _ds.Fl(),
await $W(a))},$W=async function(a){if(a.connected&&a.h){await _ds.u();var b=a.h.querySelector(".devsite-nav-active");b&&(a.hasAttribute("user-scrolled")||await bX(a,b))}},bX=async function(a,b){if(a.connected){var c=a.hasAttribute("user-scrolled");a.scrollTop=_ds.fn(b,a,!0).y;await _ds.Fl();c&&_ds.E(a,"user-scrolled","")}},UW=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:"click",label:b},bubbles:!0}))},cX=class extends _ds.F{static get observedAttributes(){return["collapsed",
"fixed","hidden"]}constructor(){super();this.connected=!1;this.ea=this.g=this.ma=this.h=null;this.oa=[];this.eventHandler=new _ds.H;this.ra=()=>{};this.o=new Set;_ds.pj(this,this.v`animatable`,this.v`aria-expanded`,this.v`aria-label`,this.v`collapsed`,this.v`data-title`,this.v`fixed`,this.v`has-book-nav`,this.v`hidden`,this.v`top-level-nav`,this.v`user-scrolled`,this.v`visually-hidden`);this.background=document.createElement("div");this.background.classList.add("devsite-book-nav-bg");this.Qb=_ds.O(EW);
this.j=_ds.O(FW);this.va=new Promise(a=>{this.ra=a});this.qa=new _ds.Pm(()=>{this.connected&&IW(this)},20);this.ua=new _ds.Pm(()=>{WW(this)},20)}async connectedCallback(){this.connected=!0;_ds.qk(this.background,this);this.hasAttribute("hidden")&&(_ds.E(this,"hidden","",this.Qb),_ds.E(this,"hidden","",this.j));let a;null==(a=this.parentElement)||a.insertBefore(this.Qb,this.nextSibling);_ds.E(this,"aria-label","Hide side navigation",this.Qb);_ds.E(this,"data-title","Hide side navigation",this.Qb);
_ds.E(this,"aria-expanded","true",this.Qb);let b;null==(b=this.parentElement)||b.insertBefore(this.j,this.nextSibling);if(this.ma=this.querySelector(".devsite-book-nav-filter"))this.g=this.ma.querySelector("input[type=text]"),this.ea=this.ma.querySelector(".filter-clear-button"),VW(this),XW(this);IW(this);QW(this);await this.init();SW(this)}disconnectedCallback(){this.connected=!1;_ds.I(this.eventHandler);TW(this);this.o.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.E(this,
"visually-hidden","",a);a=[this.background,this.Qb,this.j];for(const b of a)b&&_ds.sk(b);this.removeAttribute("animatable");this.background.removeAttribute("animatable");this.j.removeAttribute("animatable");this.j.style.removeProperty("--devsite-js-book-nav-scrollbar-width")}attributeChangedCallback(a){"hidden"===a&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if("hidden"===a||"collapsed"===a){var b=document.querySelector(".devsite-main-content");
b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.E(this,"has-book-nav","",b))}if("fixed"===a||"hidden"===a||"collapsed"===a){b=this.hasAttribute(a);const c=[this.background,this.Qb,this.j];for(const d of c)d&&(b?_ds.E(this,a,"",d):d.removeAttribute(a))}"fixed"===a&&this.ra()}async init(a=!0){if(this.connected){this.j.style.setProperty("--devsite-js-book-nav-scrollbar-width",`${this.offsetWidth-this.clientWidth}px`);this.h=this.querySelector(".devsite-mobile-nav-bottom");
_ds.E(this,"top-level-nav","");this.h&&this.h.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");0===this.children.length&&_ds.E(this,"hidden","");if(this.background)for(const b of["hidden","fixed","animatable"])this.hasAttribute(b)&&_ds.E(this,b,"",this.background);!this.hasAttribute("hidden")&&a?(YW(this),ZW(this),await aX(this)):(await _ds.Fl(),await $W(this))}}async Rb(a){a?(a=a.querySelector("nav")||null,YW(this,a),ZW(this,a),a&&(await TW(this),this.o.clear(),SW(this,a,!1)),
_ds.rj(this,this.querySelector("nav"),a)):_ds.pk(this);VW(this);if(this.g){this.g.value="";let b;null==(b=this.ea)||b.classList.add("hidden");XW(this)}await _ds.Fl();await this.init(!1)}};cX.prototype.updateContent=cX.prototype.Rb;cX.prototype.attributeChangedCallback=cX.prototype.attributeChangedCallback;cX.prototype.disconnectedCallback=cX.prototype.disconnectedCallback;cX.prototype.connectedCallback=cX.prototype.connectedCallback;try{customElements.define("devsite-book-nav",cX)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
