(function(_ds){var window=this;var o3=function(a,b){b="translate3d("+b+"px,0px,0px)";_ds.Wm(a,n3(),b)},n3=_ds.Aj(function(){return _ds.eg&&9==_ds.zg?"-ms-transform":"transform"});var r3=function(a){a.h=p3(a,".devsite-top-logo-row-wrapper-wrapper");a.g=p3(a,".devsite-collapsible-section");a.j=p3(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",`${a.h}`);a.setAttribute("bottom-row--height",`${a.g}`);a.setAttribute("bottom-tabs--height",`${a.j}`);a.style.setProperty("--devsite-js-top-row--height",`${a.h}px`);a.style.setProperty("--devsite-js-bottom-row--height",`${a.g}px`);a.style.setProperty("--devsite-js-bottom-tabs--height",`${a.j}px`);q3(a)},q3=function(a){const b=
a.querySelector(".devsite-collapsible-section");a.offset>=a.g&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<a.g-a.j&&a.hasAttribute("bottom-row--hidden")&&a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.ra&&(_ds.Wm(b,"transform",`translate3d(0, -${a.offset}px, 0)`),s3(a),a.ra=a.offset);document.body.style.setProperty("--devsite-js-header-height",`${a.o()}px`)},t3=function(a){var b=a.querySelector(".devsite-top-logo-row-middle");const c=a.querySelector("devsite-search"),
d=a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.I(a.oa);a.ea&&window.cancelAnimationFrame(a.ea);c.removeAttribute("transition");a.removeAttribute("search-expanded");var e=new _ds.Lj(b.offsetWidth,b.offsetHeight);b=new _ds.Lj(c.offsetWidth,c.offsetHeight);var f=_ds.pn(c),g="rtl"===document.documentElement.getAttribute("dir")?1:-1,h=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*g;var k=(f=a.hasAttribute("search-active"))?e:0,l=f?h:1;_ds.Wm(d,{opacity:1,width:`${b.width}px`,
height:`${b.height}px`});o3(c,a.hasAttribute("search-active")?0:e);_ds.Sm(a.oa,d,_ds.Hh,()=>{const m=a.querySelector("devsite-search"),n=a.querySelector(".devsite-search-background");n&&(n.style.opacity="0");m&&(m.removeAttribute("transition"),o3(m,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.ea=window.requestAnimationFrame(()=>{c.setAttribute("transition","");var m="scale3d("+l+",1,1)";_ds.Wm(d,n3(),m);o3(c,k)})}},u3=async function(a,
b){if(a.hasAttribute("billboard")){var c=a.querySelector("devsite-search"),d=a.querySelector("devsite-search input.devsite-search-query");a=a.querySelector(".devsite-header-billboard-search devsite-search");var e=null==a?void 0:a.querySelector("input.devsite-search-query");c&&d&&a&&e&&(b?(c.removeAttribute("disabled"),document.activeElement===e&&(await _ds.Fl(),d.focus()),a.setAttribute("disabled","")):(a.removeAttribute("disabled"),document.activeElement===d&&e.focus(),c.setAttribute("disabled",
"")))}},w3=function(a){a.eventHandler.listen(a,"devsite-search-toggle",b=>{b=b.Ea;_ds.Ik(b.target,null,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>document.body.removeAttribute("devsite-book-nav--open"));a.eventHandler.listen(window,"resize",()=>v3(a));a.eventHandler.listen(document.body,["devsite-page-loaded","devsite-content-updated"],()=>{v3(a)});a.eventHandler.listen(a,
"click",b=>{b.defaultPrevented||"devsite-hamburger-menu"!==b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",{bubbles:!0})))})},x3=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){const b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity="1";a.appendChild(b)}},s3=
function(a){0===a.g?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},v3=function(a){window.requestAnimationFrame(()=>a.ua.Ua())},p3=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},y3=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=
a.attributes.item(c),b.setAttribute(d.name,d.value)},z3=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.rj(a,c,b))},A3=class extends _ds.F{constructor(){super(...arguments);this.eventHandler=new _ds.H;this.ra=-1;this.oa=new _ds.H;this.ea=0;this.ma=new MutationObserver(()=>r3(this));this.ua=new _ds.Pm(()=>{r3(this);s3(this)},15);this.authUser=void 0;this.offset=this.j=this.g=this.h=0;this.updated=!1}static get observedAttributes(){return["offset","search-active","bottom-row--hidden"]}attributeChangedCallback(a,
b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||"")||0;q3(this);break;case "search-active":t3(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),u3(this,a)}}connectedCallback(){w3(this);x3(this);s3(this);r3(this);this.ma.observe(this,{childList:!0,subtree:!0});q3(this);
const a=_ds.G();this.authUser=_ds.fl(_ds.gl(a.href),"authuser")}disconnectedCallback(){_ds.I(this.eventHandler);this.ma.disconnect()}o(){return this.h+this.g-this.offset}qa(){return this.h+this.g}Rb(a){this.updated=!1;if(a){z3(this,a,".devsite-header-upper-tabs");z3(this,a,".devsite-collapsible-section");z3(this,a,".devsite-product-name-wrapper");z3(this,a,"devsite-language-selector");z3(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");
b&&c&&y3(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(y3(c,b),c=_ds.G(),c=_ds.fl(_ds.gl(c.href),"authuser"),c!==this.authUser&&(this.authUser=c,b.refresh()));_ds.rj(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),this.querySelector(".devsite-top-logo-row-middle"));_ds.rj(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.updated&&
a&&(_ds.pk(this),this.appendChild(a));x3(this);v3(this)}};try{customElements.define("devsite-header",A3)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
