(function(_ds){var window=this;var KZ=function(a){return!a.classList.contains("material-icons")},TZ=async function(a,b){var c=await _ds.u();const d=_ds.G();c=c.getInsecureHost();b=b.Ea;var e=b.origin===d.origin;if(c){if(b.origin!==c&&!e)return}else if(!e)return;let f;try{f=(0,_ds.Un)(b.data)}catch(g){return}c=_ds.oh(f,1);if(4===c)await LZ(a,b);else if(e=f.getName())if(e=a.querySelector(`devsite-iframe iframe[name="${e}"]`))switch(c){case 5:await MZ(b,f,e);break;case 8:await NZ(b,f,d);break;case 1:await OZ(b,f,d);break;case 6:case 7:await PZ(c,
d,f);break;case 9:await QZ(a,f);break;case 10:await RZ(f,d);break;case 13:await SZ(f)}},UZ=function(a){Array.from(a.querySelectorAll("table.lazy-load")).forEach(b=>{b.classList.remove("hidden")})},WZ=async function(a,b){if(b.detail){var c=b.detail.bottomPanelHeight,d=b.detail.contentHeight,e=b.detail.contentMargin,f=b.detail.offset,g=b.detail.panelCoversContent,h=b.detail.x;b=b.detail.y;var k=new _ds.Pn;c=_ds.th(k,8,c);d=_ds.th(c,6,d);e=_ds.th(d,7,e);f=_ds.th(e,5,f);g=_ds.sh(f,9,g);h=_ds.th(g,1,h);
h=_ds.th(h,2,b);h=_ds.th(_ds.th(h,3,_ds.hk().height),4,_ds.hk().width);b=_ds.Rn(13);h=_ds.ah(b,13,h);for(const l of a.iframes)l&&l.contentWindow&&VZ(l.contentWindow,h)}},a_=function(a){XZ(a);a.j=a.querySelector(".devsite-article-body");a.j&&(YZ(a),a.iframes=[]);a.g&&a.g.disconnect();a.h.clear();ZZ(a);if(!document.body.hasAttribute("appearance")){var b=[...a.querySelectorAll("picture > source.devsite-dark-theme")];for(var c of b){b=c.closest("picture");var d=void 0;const e=null==(d=b)?void 0:d.querySelectorAll("source:not(.devsite-dark-theme)");
let f;const g=null==(f=b)?void 0:f.querySelector("img");let h;(null==(h=e)?0:h.length)?c.remove():b&&g&&b.replaceWith(g)}}c=Array.from(a.querySelectorAll(".devsite-nav-title, .devsite-page-title, td > code, th > code"));"docs"===document.body.getAttribute("layout")&&a.j&&(d=Array.from(a.j.querySelectorAll("h1, h2, h3, h4, h5, h6")),c.push(...d));a.h.clear();a.h=new Set(c);if(_ds.G().hash){c=new _ds.qK;for(const e of a.h)_ds.pK(c,e,KZ)}else $Z(a,a.h);a.dispatchEvent(new CustomEvent("devsite-content-updated",
{bubbles:!0}))},ZZ=function(a){Array.from(a.querySelectorAll("*:not(.devsite-table-wrapper) > table")).forEach(b=>{const c=document.createElement("div");c.classList.add("devsite-table-wrapper");b.classList.contains("full-width")&&(c.classList.add("devsite-full-width-table"),b.classList.remove("full-width"));_ds.qk(c,b);c.appendChild(b)})},XZ=function(a){Array.from(a.querySelectorAll("table.lazy-load")).forEach(b=>{b.classList.add("hidden")})},LZ=async function(a,b){if(b.source){var c=b_(a,b.source);
if(c){const e="goog_"+_ds.Wj++;c.setAttribute("name",e);var d=_ds.Rn(3);d=_ds.A(d,2,e);VZ(b.source,d);(b=document.body.getAttribute("appearance"))&&c_(c,b);a.iframes.push(c)}}},MZ=async function(a,b,c){await _ds.kf();var d=_ds.jk(document).y,e=_ds.lh(b,4);const f=_ds.lh(b,3);a:{var g;if(_ds.wj&&(g=c.parentElement)){c=g;break a}g=c.parentNode;c=_ds.yf(g)&&1==g.nodeType?g:null}e&&(null==c||c.setAttribute("width",`${e}px`));f&&(null==c||c.setAttribute("height",`${f}px`));window.scrollTo({left:_ds.jk(document).x,
top:d});_ds.lf();d=new _ds.Pn;d=_ds.th(d,1,window.scrollX);d=_ds.th(_ds.th(_ds.th(d,2,window.scrollY),3,_ds.hk().height),4,_ds.hk().width);e=_ds.Rn(5);d=_ds.ah(e,13,d);b=_ds.Sn(d,_ds.z(b,8));VZ(a.source,b)},NZ=async function(a,b,c){a.source&&(b=_ds.Sn(_ds.Rn(8),_ds.z(b,8)),c=_ds.A(b,6,c.toString()),VZ(a.source,c))},OZ=async function(a,b,c){a.source&&(b=_ds.Sn(_ds.Rn(2),_ds.z(b,8)),c=_ds.A(b,7,`${c.search}${c.hash}`),VZ(a.source,c))},PZ=async function(a,b,c){const d=c.getTitle();c=new URL(c.getUrl(),
b.origin);b.search=c.search;b.hash=c.hash;b=b.href.replace(b.origin,"");6===a?_ds.sl(b,!1,!0,void 0,void 0,d):_ds.sl(b,!0,!0,void 0,void 0,d)},QZ=async function(a,b){const c=_ds.z(b,9);let d;try{d=JSON.parse(_ds.z(b,10))}catch(e){console.warn("Event data from Framebox is not valid JSON.",a);return}"analyticsEvent"===c?a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:d,bubbles:!0})):"cloudtrackEvent"===c?a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",
{detail:{eventData:d},bubbles:!0})):"devsite-apix"===c&&a.dispatchEvent(new CustomEvent("devsite-apix-observation",{detail:d,bubbles:!0}))},RZ=async function(a,b){a=a.getUrl();const c=await _ds.u();if(a){const d=new URL(a,b.origin);a.startsWith("#")||b.origin===d.origin&&b.pathname===d.pathname&&b.search===d.search?await c.scrollToAnchor(d.hash,!0):await c.fetchPage(d.href)}},SZ=async function(a){var b;const c=(null==(b=_ds.Tn(a))?void 0:_ds.lh(b,1))||0;let d;b=(null==(d=_ds.Tn(a))?void 0:_ds.lh(d,
2))||0;let e;window.scrollTo({left:c,top:b,behavior:(null==(e=_ds.Tn(a))?0:_ds.kh(e,10))?"smooth":"auto"})},VZ=function(a,b){a&&a.postMessage(_ds.xh(b),"*")},b_=function(a,b){let c;Array.from(a.querySelectorAll("devsite-iframe iframe")).forEach(d=>{_ds.yk(d)===b&&(c=d)});return c},c_=function(a,b){var c=_ds.Rn(12);b=_ds.A(c,12,b);a&&a.contentWindow&&VZ(a.contentWindow,b)},YZ=function(a){if("full"===document.body.getAttribute("layout")){let b;(a=null==(b=a.j)?void 0:b.querySelectorAll('h1[tabindex="0"],h2[tabindex="0"],h3[tabindex="0"],h4[tabindex="0"],h5[tabindex="0"],h6[tabindex="0"]'))&&
Array.from(a).forEach(c=>{c.removeAttribute("tabindex")})}},$Z=function(a,b){a.g&&b.forEach(c=>{let d;null==(d=a.g)||d.observe(c)})},d_=class extends _ds.F{constructor(){super();this.eventHandler=new _ds.H;this.o=new _ds.H;this.h=new Set;this.j=null;this.iframes=[];this.g=null;"IntersectionObserver"in window&&(this.g=new IntersectionObserver(a=>{for(const b of a)if(b.isIntersecting){a=b.target;_ds.pK(new _ds.qK,a,KZ);this.h.delete(a);let c;null==(c=this.g)||c.unobserve(a)}},{rootMargin:"100%"}))}connectedCallback(){this.eventHandler.listen(window,
"message",a=>{TZ(this,a)});this.eventHandler.listen(document.body,"devsite-appearance-updated",a=>{if(a=a.Ea.detail.preference)for(const b of this.iframes)c_(b,a)});this.eventHandler.listen(document.body,"devsite-page-loaded",()=>{UZ(this)});this.eventHandler.listen(document.body,"devsite-sticky-scroll",a=>{WZ(this,a.Ea)});a_(this)}disconnectedCallback(){this.g&&this.g.disconnect();this.h.clear();_ds.I(this.eventHandler);_ds.I(this.o)}Rb(a){a&&([".devsite-article",".devsite-content-data","devsite-content-footer",
"devsite-notification"].forEach(b=>{_ds.rj(this,this.querySelector(b),a.querySelector(b))}),a_(this),UZ(this))}};d_.prototype.updateContent=d_.prototype.Rb;d_.prototype.disconnectedCallback=d_.prototype.disconnectedCallback;d_.prototype.connectedCallback=d_.prototype.connectedCallback;try{customElements.define("devsite-content",d_)}catch(a){console.warn("devsite.app.customElement.DevsiteContent",a)};})(_ds_www);
