(function(_ds){var window=this;var g_=async function(){if("loading"===document.readyState)return new Promise(a=>{document.addEventListener("DOMContentLoaded",()=>{a()})})},h_=function(a){return!!a&&(a.classList.contains("glue-footer__global-links-list-item")||a.classList.contains("h-c-footer__global-links-list-item"))},i_=function({category:a,siteId:b},c){return d=>d.category===a&&d.siteId===b&&d.eea===c},j_=function(...a){return arguments},l_=function(a,b,c){return j_("consent",a,{ad_storage:k_(c),analytics_storage:k_(b)})},k_=
function(a=!1){return a?"granted":"denied"},m_=function(a,b=!1,c=!1,d=!1){return{event:"user_consent",cookieConsent:"UNKNOWN"===a?"none":`${"ACCEPTED"===a}`,isEEA:`${b}`,adsStorage:`${d}`,analyticsStorage:`${c}`}},n_="ar bg ca cs da de el en en-GB es es-419 et eu fi fr fr-CA gl hr hu is it iw ja ko lt lv mt nl no pl pt-BR pt-PT ro ru sk sl sr sv tr uk".split(" ");var o_={eE:"2A",fE:"2B"},p_={qy:"ACCEPTED",xD:"REJECTED",UNKNOWN:"UNKNOWN"};var q_=class{constructor(a){this.h=a;this.delay=250}debounce(){clearTimeout(this.g);this.g=window.setTimeout(this.h,this.delay)}cancel(){clearTimeout(this.g)}};window.dataLayer=window.dataLayer||[];
var r_=0,s_=function(a,b,c){a.events.dispatchEvent(new CustomEvent(b,{detail:c}))},t_=function(){try{const a=window.localStorage.getItem("glue.CookieNotificationBar"),b=a&&JSON.parse(a);return Array.isArray(b)?b.map(c=>{if(!(c instanceof Object)||Array.isArray(c))return null;const d=c.category;var e=c.date;const f=c.eea,g=c.siteId;c=c.status;return(e=e&&new Date(e))&&!isNaN(Number(e))&&Object.values(o_).includes(d)&&"string"===typeof g&&Object.values(p_).includes(c)?{category:d,date:e,eea:f,siteId:g,
status:c}:null}).filter(c=>!!c):[]}catch(a){return console.error(a),[]}},u_=async function(a){const b=await a.rendered;b instanceof HTMLElement&&a.h&&(a.visible?a.h.style.marginBottom=`${getComputedStyle(b).height}`:"0px"!==a.h.style.marginBottom&&(a.h.style.marginBottom="0px"))},v_=function(a,b){a.controls.push(...document.querySelectorAll(".glue-cookie-notification-bar-control"));for(const c of a.controls)c.addEventListener("click",a.ma),c.removeAttribute("aria-hidden"),c.setAttribute("aria-controls",
a.id),c.setAttribute("aria-expanded","false"),c.textContent=b,c instanceof HTMLButtonElement||c.addEventListener("keydown",a.oa),h_(c.parentElement)&&c.parentElement.removeAttribute("aria-hidden")},w_=class{constructor(a=document.body,b){this.root=a;this.controls=[];this.events=document.createElement("div");this.ea=!1;this.j="UNKNOWN";this.ra=!1;this.ya=c=>{this.g=c.eea;{var d=i_(this.options,this.g);const e=t_().find(d);e?(d=new Date,d.setMonth(d.getMonth()-13),d=e.date>d?e.status:"UNKNOWN"):d="UNKNOWN"}this.j=
c.required||"UNKNOWN"!==d?d:"ACCEPTED";"2A"===this.options.category&&window.dataLayer.unshift(j_("set","url_passthrough",!0),l_("default",!1,!1),l_("update",this.o,this.v),m_(this.g||!c.required?"UNKNOWN":this.status,this.g,this.o,this.v));d={required:c.required,status:this.status};this.g&&(d.eea=this.g);s_(this,"loaded",d);if(c.required)return this.listen("statuschange",this.Da),"UNKNOWN"===this.status&&this.open(),this.render(c)};this.Ba=c=>{c.preventDefault();this.status="ACCEPTED";this.close()};
this.ma=c=>{c.preventDefault();this.open(!0)};this.oa=c=>{switch(c.key){case "Enter":case " ":c.preventDefault(),this.open(!0)}};this.Ca=c=>{c.preventDefault();this.status="REJECTED";this.close()};this.Da=({detail:{status:c}})=>{if("2A"===this.options.category&&!this.g){var d="ACCEPTED"===this.status;window.dataLayer.push(l_("update",this.options.analyticsStorage||d,d),m_(this.status,this.g,this.o,this.v))}const e=i_(this.options,this.g);d=t_().filter(f=>!e(f));d.push({category:this.options.category,
date:new Date,eea:this.g,siteId:this.options.siteId,status:c});try{window.localStorage.setItem("glue.CookieNotificationBar",JSON.stringify(d))}catch(f){console.error(f)}};this.va=()=>{u_(this)};this.qa=()=>{this.Fa.debounce()};this.options=Object.assign({},w_.g,b);r_+=1;this.id=`glue-cookie-notification-bar-${r_}`;window.glueCookieNotificationBarLoaded&&this.listen("loaded",window.glueCookieNotificationBarLoaded);this.h=document.querySelector(`.${this.options.autoMarginClass}`);this.Fa=new q_(this.va);
this.config=this.fetch();this.rendered=this.config.then(this.ya)}async fetch(){const [a,b]=this.options.language.split(/[-_]/);var c=`${a}-${(b||a).toUpperCase()}`;c=n_.includes(c)?c:n_.includes(a)?a:"";const d="2A"===this.options.category?"/glue/cookienotificationbar/config/2a.json":"/glue/cookienotificationbar/config/2b.json";try{return await (await fetch(`${"https://www.gstatic.com"}${d}${c?`?hl=${c}`:""}`)).json()}catch(e){return console.error(e),{required:!1}}}async render(a){await g_();this.root||
(this.root=document.body);const b=Object.assign({},a.content,this.options.content),c=`${this.id}-label`;var d=b.mainText.replace(/\[(.+)\]/,()=>this.options.siteId);const e=document.createElement("div");e.classList.add("glue-cookie-notification-bar");e.id=this.id;e.setAttribute("aria-hidden","true");e.setAttribute("aria-labelledby",c);e.setAttribute("inert","true");e.setAttribute("role","region");e.tabIndex=-1;this.options.language!==a.language&&(e.dir=a.rtl?"rtl":"ltr",e.lang=a.language);const f=
document.createElement("p");f.classList.add("glue-cookie-notification-bar__text");e.appendChild(f);const g=document.createElement("span");g.id=c;g.textContent=`${d} `;f.appendChild(g);d=document.createElement("a");_ds.te(d,b.moreUrl);d.classList.add("glue-cookie-notification-bar__more");d.rel="noopener";d.setAttribute("aria-describedby",c);d.target="_blank";d.textContent=b.moreText;d.ariaLabel=b.moreAriaLabelText;f.appendChild(d);f.appendChild(document.createTextNode("ja"===a.language?"\u3002":"."));
a=document.createElement("button");a.addEventListener("click",this.Ba);a.classList.add("glue-cookie-notification-bar__accept");a.textContent=b.consentText;e.appendChild(a);b.rejectText&&(a=document.createElement("button"),a.addEventListener("click",this.Ca),a.classList.add("glue-cookie-notification-bar__reject"),a.textContent=b.rejectText,e.appendChild(a));b.managementText&&v_(this,b.managementText);this.h&&window.addEventListener("resize",this.qa);this.root.prepend(e);return e}get visible(){return this.ra}open(a=
!1){return this.toggle(!0,a)}close(){return this.toggle(!1)}async toggle(a,b=!1){const c=await this.rendered;if(c&&a!==this.visible){if(!this.ea){this.ea=!0;var d=document.querySelector("html");if(d){({fontSize:d}=window.getComputedStyle(d));var e=Number(d.replace("px",""));window.getComputedStyle(c).fontSize===d&&18>=e&&(c.style.fontSize=`${16/e}rem`)}}a?(c.removeAttribute("aria-hidden"),c.removeAttribute("inert"),b&&c.focus()):(c.setAttribute("aria-hidden","true"),c.setAttribute("inert","true"),
c.blur());b=`${a}`;for(const f of this.controls)f.setAttribute("aria-expanded",b);this.ra=a;s_(this,"visibilitychange",{visible:a});await u_(this)}else c&&a&&b&&c.focus()}listen(a,b){this.events.addEventListener(a,b)}unlisten(a,b){this.events.removeEventListener(a,b)}get status(){return this.j}set status(a){a!==this.j&&(this.j=a,s_(this,"statuschange",{status:a}))}get ua(){return"ACCEPTED"===this.status}get o(){return this.g||this.options.analyticsStorage||this.ua}get v(){return!this.g&&this.ua}async destroy(){const a=
await this.rendered;(null==a?0:a.parentNode)&&a.parentNode.removeChild(a);for(const b of this.controls)b.removeEventListener("click",this.ma),b.setAttribute("aria-hidden","true"),b instanceof HTMLButtonElement||b.removeEventListener("keydown",this.oa),h_(b.parentElement)&&b.parentElement.setAttribute("aria-hidden","true");this.h&&(this.h.style.marginBottom="0px",window.removeEventListener("resize",this.qa))}static get g(){return{analyticsStorage:!1,category:"2A",language:document.documentElement.lang,
siteId:location.host,autoMarginClass:"glue-footer"}}};var x_=function(){return"devsite-cookie-notification-bar"},z_=function(a){a.g&&(a.g.listen("loaded",async()=>{a.j.g();const b=await _ds.u();await b.hasMendelFlagAccess("Analytics","open_cookie_bar")&&a.g&&await a.g.open();await y_(a);await a.hasAccepted()?await b.getStorage().set("cookies_accepted","","true"):(await b.getStorage().remove("cookies_accepted",""),await _ds.Po(b.getStorage()))}),a.g.listen("visibilitychange",()=>{y_(a)}),a.g.listen("statuschange",async()=>{const b=await _ds.u();await a.hasAccepted()?
"true"!==await b.getStorage().get("cookies_accepted","")&&await b.getStorage().set("cookies_accepted","","true"):(await b.getStorage().remove("cookies_accepted",""),await _ds.Po(b.getStorage()))}))},y_=async function(a){if(a.g){var b=await a.g.rendered;b instanceof HTMLElement&&(await a.isVisible()?document.body.style.setProperty("--devsite-cookie-bar-height",getComputedStyle(b).height):document.body.style.removeProperty("--devsite-cookie-bar-height"))}},A_=class extends _ds.KI{constructor(){super(...arguments);
this.j=new _ds.jf;this.g=null;this.v=!1}Xa(){return this}async connectedCallback(){super.connectedCallback();await this.setup();z_(this)}disconnectedCallback(){super.disconnectedCallback();if(this.g){let a;null==(a=this.g)||a.destroy()}document.body.style.removeProperty("--devsite-cookie-bar-height");this.j=new _ds.jf}async setup(){const a=await _ds.u(),b=document.documentElement.lang||"en";var c=a.getConfig();const d=_ds.z(c,16),e=_ds.oh(c,30);c=_ds.kh(c,31);4===e?this.g=new w_(this,{category:"2A",
language:b,siteId:d,analyticsStorage:c}):3===e?this.g=new w_(this,{category:"2B",language:b,siteId:d,analyticsStorage:c}):await a.hasMendelFlagAccess("Analytics","open_cookie_bar")?this.g=new w_(this,{category:"2A",language:b,siteId:d,analyticsStorage:c}):(this.v=!0,this.j.g())}async hasAccepted(){await this.ready();if(this.v)return!0;let a;return"ACCEPTED"===(null==(a=this.g)?void 0:a.status)||!1}async isVisible(){await this.ready();let a;return(null==(a=this.g)?void 0:a.visible)||!1}ready(){return this.j.promise}async getCookieNotificationBar(){await this.ready();
return this.g}};A_.prototype.getCookieNotificationBar=A_.prototype.getCookieNotificationBar;A_.getTagName=x_;try{window.customElements.define(x_(),A_)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteCookieNotificationBar",a)};})(_ds_www);
